/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./shared/**/*.{js,jsx,ts,tsx}",
    "./providers/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        espresso: "#1C1108",
        "espresso-dark": "#2E2216",
        ink: "#2A1D13",
        flint: "#6B5E52",
        muted: "#8A7E74",
        ivory: "#FEFCF9",
        parchment: "#FAF8F5",
        smoke: "#EAE2D6",
        "parchment-soft": "#FBF7EF",
        cream: "#F2EBDD",
        divider: "#ECE4D7",
        dot: "#D4C7B1",
        amber: "#B86845",
        "amber-dark": "#9A5230",
        brass: "#D7B48C",
        clay: "#6B5E52",
        "clay-accent": "#B4532A",
        olive: "#6A7A43",
        "olive-dark": "#4A6A28",
        danger: "#881337",
        depth: "#4D6B8A",
        "cocoa-1": "#3A2A1F",
        "cocoa-2": "#2A1D13",
        "deep-muted": "#A89680",
        "warm-light": "#C9BCA8",
        bg: "#FBF7EF",
        "bg-app": "#FEFCF9",
        surface: "#FFFFFF",
        "surface-muted": "#FAF8F5",
        "surface-strong": "#F2EBDD",
        "surface-sunken": "#F5EDE7",
        border: "#EAE2D6",
        "border-strong": "#D4C7B1",
        text: "#1C1108",
        "text-muted": "#6B5E52",
        "text-soft": "#8A7E74",
        accent: "#B86845",
        "accent-strong": "#9A5230",
        success: "#6A7A43",
        warning: "#B86845",
        "surface-ontrip": "#F2EBDD",
        "surface-ontrip-raised": "#FAF5EA",
        "surface-ontrip-sunken": "#ECE4D7",
        "surface-exec": "#231910",
        "surface-exec-top": "#3D2E22",
        "border-ontrip": "#E4DBCB",
        "border-ontrip-strong": "#C9B99A",
        "border-exec": "#6B5743",
        "accent-ontrip": "#B85A38",
        ontrip: "#231910",
        "ontrip-strong": "#6B5743",
        "ontrip-muted": "#8A7B6A",
        "ontrip-soft": "#A89680",
        "on-dark": "#F2EBDD",
        "on-dark-muted": "#B5A892",
        "on-dark-soft": "#D89A7C",
        // DE palette additions
        "de-clay-sand": "#EFD8C9",
        "de-sage": "#94A487",
        "de-sage-deep": "#7A8B6E",
        "de-muted-light": "#B5A892",
        "de-ink-soft": "#3D2E22",
      },
      borderRadius: {
        xl2: "20px",
        xl3: "24px",
        pill: "9999px",
      },
      boxShadow: {
        card: "0 12px 40px rgba(28,17,8,0.08)",
        float: "0 18px 55px rgba(28,17,8,0.08)",
        exec: "0 20px 40px rgba(58,42,31,0.4)",
      },
    },
  },
  plugins: [],
};
