// Path: ui-mobile/features/explore/catalog.ts
// Summary: Implements catalog module logic.

import type { Destination, DestinationTheme } from "./types";

// Image URLs marked "TODO" are placeholders — replace with Unsplash or your own CDN URLs.
const CATALOG: Destination[] = [
  // ── Migrated from original catalog ──────────────────────────────────────────
  {
    id: "bali-indonesia",
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    tagline: "Temples, rice terraces & surf",
    description: "A tropical island balancing spiritual culture, lush rice terraces, surf breaks, and world-class dining.",
    bestSeason: "Apr – Oct",
    suggestedLength: "7–10 days",
    pace: "Slow city",
    themes: ["Coastal", "Culture", "Food"],
    goodFor: ["Couples", "Solo travelers", "First-time Asia trip"],
    startingNotes: "Interested in temple visits, rice terrace walks, surf lessons, and local cooking classes.",
    destination: "Bali, Indonesia",
    imageUrl: "https://images.unsplash.com/photo-1576475706812-822620fc23ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxCYWxpJTIwcmljZSUyMHRlcnJhY2VzJTIwdHJvcGljYWx8ZW58MXx8fHwxNzc2NjI1MjM0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    isEditorsPick: true,
    isFeatured: true,
  },
  {
    id: "swiss-alps-switzerland",
    name: "Swiss Alps",
    country: "Switzerland",
    region: "Europe",
    tagline: "Alpine villages & winter wonderlands",
    description: "Dramatic mountain scenery with world-class skiing, scenic rail journeys, and charming Swiss villages.",
    bestSeason: "Dec – Mar or Jun – Sep",
    suggestedLength: "5–8 days",
    pace: "Light adventure",
    themes: ["Mountain", "Light Adventure"],
    goodFor: ["Families", "Outdoor enthusiasts", "Luxury travelers"],
    startingNotes: "Interested in skiing, mountain hikes, and scenic train journeys.",
    destination: "Swiss Alps, Switzerland",
    imageUrl: "https://images.unsplash.com/photo-1734268486202-7e85b12a7fa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTd2lzcyUyMEFscHMlMjB2aWxsYWdlJTIwd2ludGVyfGVufDF8fHx8MTc3NjYzODk2NHww&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "Indian Ocean",
    tagline: "Overwater villas & coral reefs",
    description: "A remote island nation offering the ultimate in luxury beach stays, snorkeling, and marine life.",
    bestSeason: "Nov – Apr",
    suggestedLength: "5–7 days",
    pace: "Slow city",
    themes: ["Coastal"],
    goodFor: ["Couples", "Luxury travelers", "Divers"],
    startingNotes: "Interested in snorkeling, diving, and overwater villa relaxation.",
    destination: "Maldives",
    imageUrl: "https://images.unsplash.com/photo-1637576308588-6647bf80944d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxNYWxkaXZlcyUyMG92ZXJ3YXRlciUyMGJ1bmdhbG93fGVufDF8fHx8MTc3NjYzODk2NXww&ixlib=rb-4.1.0&q=80&w=1080",
    isFeatured: true,
  },
  {
    id: "iceland",
    name: "Iceland",
    country: "Iceland",
    region: "Nordic",
    tagline: "Northern lights & volcanic landscapes",
    description: "A land of fire and ice with geysers, black sand beaches, waterfalls, and aurora skies.",
    bestSeason: "Sep – Mar",
    suggestedLength: "7–10 days",
    pace: "Light adventure",
    themes: ["Mountain", "Light Adventure", "Off-the-beaten-path"],
    goodFor: ["Adventurers", "Photographers", "Nature lovers"],
    startingNotes: "Interested in northern lights, hot springs, waterfalls, and Ring Road drives.",
    destination: "Iceland",
    imageUrl: "https://images.unsplash.com/photo-1681834418277-b01c30279693?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJY2VsYW5kJTIwbm9ydGhlcm4lMjBsaWdodHMlMjBhdXJvcmF8ZW58MXx8fHwxNzc2NjM4OTY1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "queenstown-new-zealand",
    name: "Queenstown",
    country: "New Zealand",
    region: "Pacific",
    tagline: "Lakes, mountains & adrenaline",
    description: "Adventure capital of the world, offering bungee jumping, skiing, lake cruises, and Fiordland access.",
    bestSeason: "Nov – Apr",
    suggestedLength: "4–7 days",
    pace: "Light adventure",
    themes: ["Mountain", "Light Adventure", "Coastal"],
    goodFor: ["Adventurers", "Families", "Outdoor fans"],
    startingNotes: "Interested in adventure sports, scenic cruises, and national park access.",
    destination: "Queenstown, New Zealand",
    imageUrl: "https://images.unsplash.com/photo-1646369987506-383d96fce566?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxOZXclMjBaZWFsYW5kJTIwbW91bnRhaW5zJTIwbGFrZXxlbnwxfHx8fDE3NzY2Mzg5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "machu-picchu-peru",
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    tagline: "Inca ruins above the clouds",
    description: "One of the world's great archaeological sites, surrounded by cloud forest and Sacred Valley villages.",
    bestSeason: "May – Sep",
    suggestedLength: "3–5 days",
    pace: "Light adventure",
    themes: ["Culture", "Mountain", "Light Adventure"],
    goodFor: ["History lovers", "Hikers", "Adventure seekers"],
    startingNotes: "Interested in Inca Trail hiking, archaeological sites, and Sacred Valley exploration.",
    destination: "Machu Picchu, Peru",
    imageUrl: "https://images.unsplash.com/photo-1586367443498-8d0aa9de31bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQZXJ1JTIwTWFjaHUlMjBQaWNjaHUlMjBydWluc3xlbnwxfHx8fDE3NzY2Mzg5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "dubrovnik-croatia",
    name: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    tagline: "Adriatic gem & walled old town",
    description: "A stunning medieval city with iconic city walls, island day trips, and Adriatic coastline.",
    bestSeason: "May – Sep",
    suggestedLength: "4–6 days",
    pace: "Slow city",
    themes: ["Culture", "Coastal"],
    goodFor: ["Couples", "History buffs", "Beach lovers"],
    startingNotes: "Interested in city wall walks, island excursions, and seafood dining.",
    destination: "Dubrovnik, Croatia",
    imageUrl: "https://images.unsplash.com/photo-1655560585033-67e928edd1f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxDcm9hdGlhJTIwRHVicm92bmlrJTIwb2xkJTIwdG93bnxlbnwxfHx8fDE3NzY2Mzg5NzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "serengeti-tanzania",
    name: "Serengeti",
    country: "Tanzania",
    region: "Africa",
    tagline: "Safari sunsets & the great migration",
    description: "Africa's most iconic wildlife destination with vast plains, the Big Five, and epic migration spectacles.",
    bestSeason: "Jun – Oct",
    suggestedLength: "5–7 days",
    pace: "Off-the-beaten-path",
    themes: ["Light Adventure", "Off-the-beaten-path"],
    goodFor: ["Adventurers", "Wildlife enthusiasts", "Photographers"],
    startingNotes: "Interested in game drives, wildlife photography, and luxury safari camps.",
    destination: "Serengeti, Tanzania",
    imageUrl: "https://images.unsplash.com/photo-1595652973888-c5677816f6f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWZhcmklMjBzdW5zZXQlMjBBZnJpY2ElMjBzYXZhbm5hfGVufDF8fHx8MTc3NjYzODk2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "provence-france",
    name: "Provence",
    country: "France",
    region: "Europe",
    tagline: "Lavender fields & village markets",
    description: "A sun-drenched region known for fragrant lavender, rosé wine, and charming hilltop villages.",
    bestSeason: "Jun – Aug",
    suggestedLength: "5–7 days",
    pace: "Slow city",
    themes: ["Food", "Culture", "Slow City"],
    goodFor: ["Couples", "Foodies", "Slow travelers"],
    startingNotes: "Interested in lavender fields, wine tastings, and village markets.",
    destination: "Provence, France",
    imageUrl: "https://images.unsplash.com/photo-1662486717731-293f2b6ebfa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxQcm92ZW5jZSUyMGxhdmVuZGVyJTIwZmllbGRzJTIwRnJhbmNlfGVufDF8fHx8MTc3NjYzODk2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "halong-bay-vietnam",
    name: "Halong Bay",
    country: "Vietnam",
    region: "Southeast Asia",
    tagline: "Emerald waters & limestone karsts",
    description: "A UNESCO World Heritage site offering dramatic seascapes, cave exploration, and overnight cruise experiences.",
    bestSeason: "Oct – Apr",
    suggestedLength: "2–3 days",
    pace: "Slow city",
    themes: ["Coastal", "Culture"],
    goodFor: ["Couples", "Nature lovers", "First-time Asia trip"],
    startingNotes: "Interested in overnight cruises, kayaking, and cave exploration.",
    destination: "Halong Bay, Vietnam",
    imageUrl: "https://images.unsplash.com/photo-1713551584340-7b7817f39a62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxWaWV0bmFtJTIwSGFsb25nJTIwQmF5JTIwYm9hdHN8ZW58MXx8fHwxNzc2NjM4OTY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
  },
  {
    id: "scottish-highlands-scotland",
    name: "Scottish Highlands",
    country: "Scotland",
    region: "Europe",
    tagline: "Castles, lochs & misty glens",
    description: "Wild and remote landscapes dotted with ancient castles, whisky distilleries, and legendary lochs.",
    bestSeason: "May – Sep",
    suggestedLength: "5–7 days",
    pace: "Off-the-beaten-path",
    themes: ["Mountain", "Culture", "Off-the-beaten-path"],
    goodFor: ["Road trippers", "Hikers", "History buffs"],
    startingNotes: "Interested in distillery tours, castle visits, and scenic driving routes.",
    destination: "Scottish Highlands, Scotland",
    imageUrl: "https://images.unsplash.com/photo-1694086561623-1463e2cf2102?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxTY290dGlzaCUyMEhpZ2hsYW5kcyUyMGNhc3RsZSUyMGxhbmRzY2FwZXxlbnwxfHx8fDE3NzY2Mzg5ODB8MA&ixlib=rb-4.1.0&q=80&w=1080",
  },

  // ── From places.txt ──────────────────────────────────────────────────────────
  // Note: imageUrl values marked "TODO" need a real Unsplash (or CDN) URL.
  {
    id: "lisbon-portugal",
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    tagline: "Pastel streets, ocean air, and late dinners.",
    description: "A warm coastal city for relaxed neighborhoods, food, viewpoints, and easy day trips.",
    bestSeason: "Spring or fall",
    suggestedLength: "4–6 days",
    pace: "Slow city",
    themes: ["Coastal", "Food", "Culture"],
    goodFor: ["First-time Europe trip", "Couples", "Small groups"],
    startingNotes: "Interested in coastal walks, neighborhood food spots, viewpoints, and relaxed day trips.",
    destination: "Lisbon, Portugal",
    imageUrl: "https://images.unsplash.com/photo-1738970361018-848be032aa09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxMaXNib24lMjBQb3J0dWdhbCUyMGNvbG9yZnVsJTIwc3RyZWV0c3xlbnwxfHx8fDE3NzY2Mzg5NjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "hoi-an-vietnam",
    name: "Hoi An",
    country: "Vietnam",
    region: "Asia",
    tagline: "Silk lanterns, ancient architecture, and yellow alleyways.",
    description: "A well-preserved trading port known for tailor shops, riverside dining, and colorful evening markets.",
    bestSeason: "February to April",
    suggestedLength: "3–4 days",
    pace: "Slow city",
    themes: ["Culture", "Food", "Coastal"],
    goodFor: ["First-time Asia trip", "Couples", "Photography enthusiasts"],
    startingNotes: "Interested in custom tailoring, night markets, and lantern-lit river walks.",
    destination: "Hoi An, Vietnam",
    imageUrl: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    tagline: "Zen gardens, traditional shrines, and seasonal blooms.",
    description: "A serene cultural capital defined by historic districts, bamboo forests, and refined tea ceremonies.",
    bestSeason: "Spring or fall",
    suggestedLength: "4–5 days",
    pace: "Slow city",
    themes: ["Culture", "Slow City"],
    goodFor: ["Solo travelers", "History buffs", "Nature lovers"],
    startingNotes: "Interested in temple visits, garden walks, and traditional kaiseki dining.",
    destination: "Kyoto, Japan",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
    isFeatured: true,
  },
  {
    id: "sedona-usa",
    name: "Sedona",
    country: "USA",
    region: "North America",
    tagline: "Red rock vistas, desert trails, and starry skies.",
    description: "A desert oasis offering striking geology, world-class hiking, and tranquil wellness retreats.",
    bestSeason: "Spring or fall",
    suggestedLength: "3–4 days",
    pace: "Light adventure",
    themes: ["Desert", "Mountain", "Light Adventure"],
    goodFor: ["Hikers", "Wellness seekers", "Road trippers"],
    startingNotes: "Interested in trail hiking, energy vortexes, and sunset viewpoints.",
    destination: "Sedona, USA",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "oaxaca-mexico",
    name: "Oaxaca",
    country: "Mexico",
    region: "North America",
    tagline: "Vibrant textiles, artisanal mezcal, and colonial charm.",
    description: "A colorful hub for traditional crafts, regional cuisine, and ancient Zapotec archaeological sites.",
    bestSeason: "Late fall or winter",
    suggestedLength: "5–7 days",
    pace: "Slow city",
    themes: ["Food", "Culture"],
    goodFor: ["Foodies", "Art collectors", "Culture seekers"],
    startingNotes: "Interested in market tours, mezcal tastings, and textile workshops.",
    destination: "Oaxaca, Mexico",
    imageUrl: "https://images.unsplash.com/photo-1518638150340-f706e86654de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "bergen-norway",
    name: "Bergen",
    country: "Norway",
    region: "Europe",
    tagline: "Fjord gateway, colorful wharves, and mountain trails.",
    description: "A historic harbor city nestled between mountains, offering access to dramatic fjords and seafood.",
    bestSeason: "Summer",
    suggestedLength: "3–5 days",
    pace: "Light adventure",
    themes: ["Mountain", "Coastal", "Culture"],
    goodFor: ["Families", "Outdoor enthusiasts", "Photographers"],
    startingNotes: "Interested in fjord cruises, funicular rides, and waterfront exploring.",
    destination: "Bergen, Norway",
    imageUrl: "https://images.unsplash.com/photo-1531253655765-98d3c8a51a1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "udaipur-india",
    name: "Udaipur",
    country: "India",
    region: "Asia",
    tagline: "Floating palaces, lake views, and royal heritage.",
    description: "A romantic lakeside city known for its intricate temples, boat cruises, and sunset terrace dining.",
    bestSeason: "October to March",
    suggestedLength: "3–4 days",
    pace: "Slow city",
    themes: ["Culture", "Slow City"],
    goodFor: ["Couples", "Luxury travelers", "History buffs"],
    startingNotes: "Interested in boat trips, palace architecture, and traditional crafts.",
    destination: "Udaipur, India",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "lofoten-islands-norway",
    name: "Lofoten Islands",
    country: "Norway",
    region: "Europe",
    tagline: "Arctic peaks, fishing cabins, and crystal waters.",
    description: "Remote archipelago offering dramatic landscapes, northern lights, and coastal hiking in the Arctic.",
    bestSeason: "Summer or winter",
    suggestedLength: "5–7 days",
    pace: "Off-the-beaten-path",
    themes: ["Off-the-beaten-path", "Coastal", "Mountain"],
    goodFor: ["Adventurers", "Photographers", "Nature lovers"],
    startingNotes: "Interested in hiking, coastal drives, and cabin stays.",
    destination: "Lofoten Islands, Norway",
    imageUrl: "https://images.unsplash.com/photo-1520769945061-0a448c463865?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
    isFeatured: true,
  },
  {
    id: "bozeman-usa",
    name: "Bozeman",
    country: "USA",
    region: "North America",
    tagline: "Big Sky landscapes, river trails, and wild peaks.",
    description: "An adventurous basecamp for Yellowstone, fly fishing, and western hospitality in Montana.",
    bestSeason: "Summer or winter",
    suggestedLength: "4–6 days",
    pace: "Light adventure",
    themes: ["Mountain", "Light Adventure"],
    goodFor: ["Families", "Outdoor fans", "National park visitors"],
    startingNotes: "Interested in park access, fly fishing, and trail hiking.",
    destination: "Bozeman, USA",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "luang-prabang-laos",
    name: "Luang Prabang",
    country: "Laos",
    region: "Asia",
    tagline: "Mekong sunsets, golden temples, and morning rituals.",
    description: "A peaceful riverside town merging colonial style with Buddhist tradition and lush waterfalls.",
    bestSeason: "November to February",
    suggestedLength: "4–5 days",
    pace: "Slow city",
    themes: ["Culture", "Slow City"],
    goodFor: ["Quiet travelers", "Solo travelers", "Spiritual seekers"],
    startingNotes: "Interested in river cruises, temple walks, and night markets.",
    destination: "Luang Prabang, Laos",
    imageUrl: "https://images.unsplash.com/photo-1568555450649-9fa88aa53a72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "san-sebastian-spain",
    name: "San Sebastian",
    country: "Spain",
    region: "Europe",
    tagline: "World-class pintxos, urban surfing, and bay views.",
    description: "A premier food destination with elegant beaches and a vibrant Basque culture.",
    bestSeason: "June to September",
    suggestedLength: "3–5 days",
    pace: "Slow city",
    themes: ["Food", "Coastal", "Culture"],
    goodFor: ["Foodies", "Beach lovers", "Groups"],
    startingNotes: "Interested in tapas crawling, beach walks, and coastal hikes.",
    destination: "San Sebastian, Spain",
    imageUrl: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "wadi-rum-jordan",
    name: "Wadi Rum",
    country: "Jordan",
    region: "Middle East",
    tagline: "Ancient petroglyphs, red dunes, and desert camps.",
    description: "A Mars-like wilderness perfect for jeep tours, camel treks, and sleeping under the stars.",
    bestSeason: "Spring or fall",
    suggestedLength: "2–3 days",
    pace: "Off-the-beaten-path",
    themes: ["Desert", "Off-the-beaten-path"],
    goodFor: ["Adventure seekers", "Unique stays", "Stargazers"],
    startingNotes: "Interested in desert camping, history, and photography.",
    destination: "Wadi Rum, Jordan",
    imageUrl: "https://images.unsplash.com/photo-1544735716-ea9ef867c3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "dolomites-italy",
    name: "Dolomites",
    country: "Italy",
    region: "Europe",
    tagline: "Jagged limestone peaks, alpine huts, and lakes.",
    description: "Breathtaking mountain scenery offering world-class hiking, scenic drives, and refined mountain cuisine.",
    bestSeason: "Summer or winter",
    suggestedLength: "5–8 days",
    pace: "Light adventure",
    themes: ["Mountain", "Light Adventure"],
    goodFor: ["Hikers", "Nature lovers", "Photographers"],
    startingNotes: "Interested in mountain passes, hiking trails, and lake views.",
    destination: "Dolomites, Italy",
    imageUrl: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "galle-sri-lanka",
    name: "Galle",
    country: "Sri Lanka",
    region: "Asia",
    tagline: "Dutch fort walls, ocean breezes, and lighthouses.",
    description: "A coastal fortress town blending colonial history with tropical beaches and boutique charm.",
    bestSeason: "December to April",
    suggestedLength: "3–5 days",
    pace: "Slow city",
    themes: ["Coastal", "Culture", "Slow City"],
    goodFor: ["History lovers", "Couples", "Slow travelers"],
    startingNotes: "Interested in fort walks, beach relaxation, and boutique shopping.",
    destination: "Galle, Sri Lanka",
    imageUrl: "https://images.unsplash.com/photo-1566296314736-6eef3a9f50c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "annecy-france",
    name: "Annecy",
    country: "France",
    region: "Europe",
    tagline: "Alpine canals, turquoise lakes, and mountain air.",
    description: "Known as the Venice of the Alps, this town offers lakeside charm and proximity to mountains.",
    bestSeason: "Summer or fall",
    suggestedLength: "3–4 days",
    pace: "Slow city",
    themes: ["Mountain", "Slow City", "Food"],
    goodFor: ["Romance", "Families", "Nature lovers"],
    startingNotes: "Interested in lake sports, old town walks, and local cheese.",
    destination: "Annecy, France",
    imageUrl: "https://images.unsplash.com/photo-1571757759445-8bb4a43d31c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "atacama-desert-chile",
    name: "Atacama Desert",
    country: "Chile",
    region: "South America",
    tagline: "Moon valleys, salt flats, and high-altitude geysers.",
    description: "The driest desert on earth, featuring unearthly landscapes and world-class stargazing.",
    bestSeason: "Spring or fall",
    suggestedLength: "4–6 days",
    pace: "Off-the-beaten-path",
    themes: ["Desert", "Off-the-beaten-path", "Light Adventure"],
    goodFor: ["Adventurers", "Photographers", "Stargazers"],
    startingNotes: "Interested in salt flats, geysers, and desert tours.",
    destination: "Atacama Desert, Chile",
    imageUrl: "https://images.unsplash.com/photo-1566204773863-cf63e6d4ab58?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "essaouira-morocco",
    name: "Essaouira",
    country: "Morocco",
    region: "Africa",
    tagline: "Blue-and-white medinas, windy beaches, and fresh fish.",
    description: "A relaxed coastal town known for its medina walls, art galleries, and surfing.",
    bestSeason: "Spring or summer",
    suggestedLength: "3–5 days",
    pace: "Slow city",
    themes: ["Coastal", "Culture", "Food"],
    goodFor: ["Solo travelers", "Artists", "Beach enthusiasts"],
    startingNotes: "Interested in medina walks, seaside dining, and windsurfing.",
    destination: "Essaouira, Morocco",
    imageUrl: "https://images.unsplash.com/photo-1538650702931-c15fe4b84b8d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "tallinn-estonia",
    name: "Tallinn",
    country: "Estonia",
    region: "Europe",
    tagline: "Medieval spires, cobblestones, and modern design.",
    description: "A fairytale old town meeting digital-forward culture on the edge of the Baltic Sea.",
    bestSeason: "Summer",
    suggestedLength: "2–4 days",
    pace: "Slow city",
    themes: ["Culture", "Slow City"],
    goodFor: ["City breakers", "History buffs", "Tech fans"],
    startingNotes: "Interested in castle tours, viewpoint walks, and cozy cafes.",
    destination: "Tallinn, Estonia",
    imageUrl: "https://images.unsplash.com/photo-1565266400521-cbc90c60b05c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "antigua-guatemala",
    name: "Antigua",
    country: "Guatemala",
    region: "Central America",
    tagline: "Volcano backdrops, colonial ruins, and coffee scents.",
    description: "A UNESCO-listed city surrounded by volcanoes, famous for its colorful streets and coffee culture.",
    bestSeason: "November to April",
    suggestedLength: "4–6 days",
    pace: "Slow city",
    themes: ["Culture", "Mountain", "Food"],
    goodFor: ["Language learners", "Backpackers", "Photographers"],
    startingNotes: "Interested in volcano hikes, ruins, and coffee tours.",
    destination: "Antigua, Guatemala",
    imageUrl: "https://images.unsplash.com/photo-1617169444296-3e8d0c06e39e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "isle-of-skye-scotland",
    name: "Isle of Skye",
    country: "Scotland",
    region: "Europe",
    tagline: "Mist-covered glens, rugged cliffs, and fairy pools.",
    description: "A dramatic island landscape offering some of the UK's best hiking and coastal views.",
    bestSeason: "May to September",
    suggestedLength: "3–5 days",
    pace: "Off-the-beaten-path",
    themes: ["Off-the-beaten-path", "Mountain", "Coastal"],
    goodFor: ["Hikers", "Road trippers", "Nature lovers"],
    startingNotes: "Interested in hiking, scenic drives, and local distilleries.",
    destination: "Isle of Skye, Scotland",
    imageUrl: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "mendoza-argentina",
    name: "Mendoza",
    country: "Argentina",
    region: "South America",
    tagline: "Andean peaks, Malbec vineyards, and open-air asados.",
    description: "Argentina's wine capital offering vineyard tours and mountain adventures under the high Andes.",
    bestSeason: "March to May",
    suggestedLength: "4–6 days",
    pace: "Slow city",
    themes: ["Food", "Mountain", "Light Adventure"],
    goodFor: ["Wine lovers", "Couples", "Mountain fans"],
    startingNotes: "Interested in winery tours, biking, and mountain views.",
    destination: "Mendoza, Argentina",
    imageUrl: "https://images.unsplash.com/photo-1548280977-0f1b49c87a37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "quebec-city-canada",
    name: "Quebec City",
    country: "Canada",
    region: "North America",
    tagline: "French charm, fortified walls, and winter magic.",
    description: "A historic, European-feeling city in North America known for architecture, culture, and cobblestone streets.",
    bestSeason: "Summer or winter",
    suggestedLength: "3–5 days",
    pace: "Slow city",
    themes: ["Culture", "Slow City", "Food"],
    goodFor: ["Couples", "History buffs", "City breakers"],
    startingNotes: "Interested in old town walks, historic sites, and seasonal festivals.",
    destination: "Quebec City, Canada",
    imageUrl: "https://images.unsplash.com/photo-1519972064555-542444e71b54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "chefchaouen-morocco",
    name: "Chefchaouen",
    country: "Morocco",
    region: "Africa",
    tagline: "Blue-washed walls, mountain trails, and quiet medinas.",
    description: "The famous blue city of the Rif Mountains, offering a calm atmosphere and beautiful trekking.",
    bestSeason: "Spring or fall",
    suggestedLength: "2–3 days",
    pace: "Slow city",
    themes: ["Culture", "Mountain", "Off-the-beaten-path"],
    goodFor: ["Solo travelers", "Photographers", "Culture seekers"],
    startingNotes: "Interested in photography, mountain hiking, and market exploring.",
    destination: "Chefchaouen, Morocco",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
  {
    id: "cusco-peru",
    name: "Cusco",
    country: "Peru",
    region: "South America",
    tagline: "Inca ruins, cobblestone lanes, and Andean spirit.",
    description: "The historic heart of the Inca Empire and a base for exploring the Sacred Valley.",
    bestSeason: "May to September",
    suggestedLength: "5–7 days",
    pace: "Light adventure",
    themes: ["Culture", "Mountain", "Light Adventure"],
    goodFor: ["History lovers", "Hikers", "Adventure seekers"],
    startingNotes: "Interested in ruins, traditional markets, and high-altitude hiking.",
    destination: "Cusco, Peru",
    imageUrl: "https://images.unsplash.com/photo-1580823009723-bbba6ec2b75e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    isEditorsPick: true,
  },
];

function normalizeForSearch(d: Destination): string {
  return [d.name, d.country, d.region, d.tagline, d.description, d.pace, ...d.themes, ...d.goodFor]
    .join(" ")
    .toLowerCase();
}

export function listDestinationThemes(): DestinationTheme[] {
  return [
    "Coastal",
    "Food",
    "Culture",
    "Slow City",
    "Desert",
    "Mountain",
    "Light Adventure",
    "Off-the-beaten-path",
  ];
}

export function getDestinations(filters: {
  query?: string;
  theme?: DestinationTheme | null;
} = {}): Destination[] {
  const { query = "", theme = null } = filters;
  const q = query.trim().toLowerCase();

  return CATALOG.filter((d) => {
    const matchesQuery = q ? normalizeForSearch(d).includes(q) : true;
    const matchesTheme = theme ? d.themes.includes(theme) : true;
    return matchesQuery && matchesTheme;
  });
}

export function getFeaturedDestinations(): Destination[] {
  return CATALOG.filter((d) => d.isFeatured);
}
